### ISSUE TITLE
Specifying headers and relying on $_SERVER

### ISSUE THREAD

**Issue by jeanatpi** [zenstruck/browser#157]
Hello,

I was trying to do a test on a controller using Mobile Detect lib (https://github.com/serbanghita/Mobile-Detect).

Like this:

```
$browser
->interceptRedirects()
->actingAs($user->_real())
->get('/', [
  'headers' => [
     'User-Agent' => 'blabla'
  ]
]);
```

However mobile detect lib seems to use $_SERVER to do his job, so $_SERVER['HTTP_USER_AGENT'].
And using $browser as before does not seems to change $_SERVER. So I end up adding the following before my test:

`$_SERVER['HTTP_USER_AGENT'] = 'blabla'`

Which is working but not great as I also need to reset this value for any other tests in the same class.

I was wondering if I'm using the library the wrong way (zenstruck browser) or if there's anything that can be improved.

Regards,

Jean

**Comment by nikophil** [comment]
Hello @jeanatpi 

`zenstruck/browser` is using `symfony/browser-kit` to perform faked http requests, and they don't modify the super globals (`$_GET`, `$_SERVER`, etc...). 

As far as I can see, you're using the library the good way, but relying on super globals is not really the "symfony-way" and it is not a good practice. I'm very surprised that a so popular library is relying on super globals without any way to mitigate this.

[In the docs](https://docs.mobiledetect.net/home/mobile-detect-ports), they are advertising for some bundle, maybe you can use one of them?
If this is not a solution, maybe you can [override](https://github.com/zenstruck/browser?tab=readme-ov-file#extending) `Browser::request()` method, detect the presence of a user agent in the headers and fill `$_SERVER` here, so that this will be automatically done once for all, but I don't think we want to mess up with super globals is this library
